name: Crowdin Action

on:
  push:
    branches: [ main ]

jobs:
  crowdin:
    strategy:
      max-parallel: 1
    name: "Synchronize Crowdin Localizations"
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Crowdin Action
      uses: crowdin/github-action@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      with:
        upload_sources: false
        upload_translations: false
        download_translations: true

        skip_untranslated_strings: true
        export_only_approved: true
        push_translations: true
        commit_message: 'New Crowdin translations by Github Action'

        create_pull_request: true
        localization_branch_name: l10n_crowdin_translations
        pull_request_title: 'New Crowdin Translations'
        pull_request_base_branch_name: 'main'
        pull_request_labels: 'translations'
        pull_request_assignees: 'crowdin-bot'
        pull_request_reviewers: 'vivekjoshy'

        pull_request_body: |
            **This is an automated PR.**

            This PR updates the translations using content from Crowdin. Thanks to all the translators for the really hard work!
            If you want to help to make the localization better, or add a new language, go to [Crowdin](https://crowdin.com/project/openskill) and start helping!.

            [![Crowdin](https://badges.crowdin.net/openskill/localized.svg)](https://crowdin.com/project/openskill)
