name: Tests
on: [push, pull_request]
jobs:
  tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, MacOS, Windows]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        experimental: [false]
        include:
          - os: Ubuntu
            python-version: "3.11-dev"
            experimental: true
          - os: MacOS
            python-version: "3.11-dev"
            experimental: true
          - os: Windows
            python-version: "3.11-dev"
            experimental: true
    defaults:
      run:
        shell: bash
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'
        - name: Set ENV
          run: |
              echo "MKL_CBWR=AUTO" >> $GITHUB_ENV
              echo "PYTHONHASHSEED=0" >> $GITHUB_ENV
        - name: Run Tests
          run: |
              python -m pip install --upgrade pip
              pip install -e.[docs,tests,release]
              python -m pip install --upgrade build
              python -m build
              twine check dist/*
              black --check .
              pytest . --cov --cov-report=term-missing -vv
              coverage report
              coverage html
              coverage xml --ignore-errors
          continue-on-error: ${{ matrix.experimental }}
        - name: "Upload coverage to Codecov"
          uses: codecov/codecov-action@v2
          with:
            fail_ci_if_error: ${{ !matrix.experimental }}
